
'use strict';function log(b){logContent.insertAdjacentHTML("beforeend","\x3cdiv\x3e"+b+"\x3c/div\x3e")}let isManualDisconect=!1,deviceCache=null,characteristicCache=null;function connect(){navigator.bluetooth.getAvailability().then(b=>{b?(deviceCache?Promise.resolve(deviceCache):requestBluetoothDevice()).then(a=>connectDeviceAndCacheCharacteristic(a)).catch(a=>{log(a);bltNotFoundDlg.showModal()}):(log("Bluetooth is unavailable"),unavailableBltDlg.showModal())}).catch(b=>log(b))}
function requestBluetoothDevice(){log("Requesting bluetooth device...");return navigator.bluetooth.requestDevice({filters:[{name:["Vika-1"]}],optionalServices:[65280]}).then(b=>{log('"'+b.name+'" bluetooth device selected');deviceCache=b;deviceCache.addEventListener("gattserverdisconnected",handleDisconnection);return deviceCache})}
function handleDisconnection(b){connectControls.classList.remove("hidden");disconnectControls.classList.add("hidden");saveGamesBtn.disabled=!0;isManualDisconect||(b=b.target,log('"'+b.name+'" bluetooth device disconnected, trying to reconnect...'),connectDeviceAndCacheCharacteristic(b).catch(a=>log(a)))}
function connectDeviceAndCacheCharacteristic(b){isManualDisconect=!1;if(b.gatt.connected&&characteristicCache)return Promise.resolve(characteristicCache);log("Connecting to GATT server...");return b.gatt.connect().then(a=>{log("GATT server connected, getting service...");connectControls.classList.add("hidden");disconnectControls.classList.remove("hidden");saveGamesBtn.disabled=!1;return a.getPrimaryService(65280)}).then(a=>{log("Service found, getting characteristic...");return a.getCharacteristic(65281)}).then(a=>
{log("Characteristic found");return characteristicCache=a})}function disconnect(){isManualDisconect=!0;deviceCache?(log('Disconnecting from "'+deviceCache.name+'" bluetooth device...'),deviceCache.gatt.connected?(deviceCache.gatt.disconnect(),log('"'+deviceCache.name+'" bluetooth device disconnected')):log('"'+deviceCache.name+'" bluetooth device is already disconnected')):log("Bluetooth device is already disconnected")}
function checkMinMax(b){let a=b.value.trim();if(""===a||isNaN(a))a=b.getAttribute("value");a=Math.min(Math.max(a,b.min),b.max);b.value!=a&&(b.value=a)}
function saveGameRules(){log("Save game rules...");if(characteristicCache){var b=document.querySelector(".tabs").children,a=new Uint8Array(24*b.length),c=0;for(let g=0;g<b.length;g++){let d=b[g].elements;var e=void 0;e="GT_ALL_PRESS"==d.gameType.value?1:0;b[g].classList.contains("active")&&(e|=128);a[c++]=e;a[c++]="TA_AFTER_QUESTION_START"==d.takeAnswer.value?1:0;a[c++]=d.falseStart.checked?1:0;a[c++]="FSB_TEMPORARILY"==d.falseStartBlock.value?1:0;e=Number(d.falseStartBlockTime.value);isNaN(e)&&(e=
5);a[c++]=e;a[c++]=d.firstSecondRule.checked?1:0;a[c++]="OWA_NEXT_QUESTION"==d.onWrongAnswer.value?1:0;a[c++]="ONP_NEXT_ALREADY_PRESSED"==d.onNextPlayer.value?1:0;a[c++]="ORT_FULL_TIME"==d.onRestartThinkingTime.value?1:0;e="TM_UNLIMIT"==d.thinkingTimeMode.value?255:Number(d.thinkingTime.value);isNaN(e)&&(e=30);a[c++]=e;e="TM_UNLIMIT"==d.answerTimeMode.value?255:Number(d.answerTime.value);isNaN(e)&&(e=30);a[c++]=e;a[c++]=d.showFalseStart.checked?1:0;a[c++]=d.showWrongAnswer.checked?1:0;a[c++]=d.showNextReadyToAnswer.checked?
1:0;a[c++]=d.sndQuestion.checked?1:0;a[c++]=d.sndStartThinking.checked?1:0;a[c++]=d.sndThinkingTimeout.checked?1:0;a[c++]=d.sndAnswerTimeout.checked?1:0;a[c++]=d.sndPlayerButton.checked?1:0;a[c++]=d.sndRightAnswer.checked?1:0;a[c++]=d.sndWrongAnswer.checked?1:0;a[c++]=d.sndFalseStart.checked?1:0;a[c++]=d.sndClock.checked?1:0;a[c++]=d.sndTikTok.checked?1:0}characteristicCache.writeValueWithResponse(a).then(()=>{log("Game rules saved")})}else log("Characteristic not found")}
function getGameRules(){log("Get game rules...");characteristicCache?characteristicCache.readValue().then(b=>{log("Game rules received");document.querySelectorAll(".tabs\x3e*, .tab-selector\x3e*:not(#addGameBtn)").forEach(e=>{e.remove()});addGameBtn.classList.remove("hidden");deleteGameBtn.classList.add("hidden");b=new Uint8Array(b.buffer);let a=Math.min(Math.floor(b.length/24),6),c=0;for(let e=0;e<a&&255!=b[c];e++){let g=addGame(),d=g.elements,f;d.gameType.value=1==b[c++]?"GT_ALL_PRESS":"GT_FIRST_PRESS";
d.takeAnswer.value=1==b[c++]?"TA_AFTER_QUESTION_START":"TA_AFTER_SIGNAL";d.falseStart.checked=0!=b[c++];d.falseStartBlock.value=1==b[c++]?"FSB_TEMPORARILY":"FSB_FULL";f=Number(b[c++]);isNaN(f)&&(f=5);d.falseStartBlockTime.value=f;d.firstSecondRule.checked=0!=b[c++];d.onWrongAnswer.value=1==b[c++]?"OWA_NEXT_QUESTION":"OWA_NEXT_PLAYER";d.onNextPlayer.value=1==b[c++]?"ONP_NEXT_ALREADY_PRESSED":"ONP_RESTART_THINKING_TIME";d.onRestartThinkingTime.value=1==b[c++]?"ORT_FULL_TIME":"ORT_REMAINDER";f=Number(b[c++]);
isNaN(f)&&(f=30);d.thinkingTime.value=f;d.thinkingTimeMode.value=255==f?"TM_UNLIMIT":"TM_LIMIT";f=Number(b[c++]);isNaN(f)&&(f=30);d.answerTime.value=f;d.answerTimeMode.value=255==f?"TM_UNLIMIT":"TM_LIMIT";d.showFalseStart.checked=0!=b[c++];d.showWrongAnswer.checked=0!=b[c++];d.showNextReadyToAnswer.checked=0!=b[c++];d.sndQuestion.checked=0!=b[c++];d.sndStartThinking.checked=0!=b[c++];d.sndThinkingTimeout.checked=0!=b[c++];d.sndAnswerTimeout.checked=0!=b[c++];d.sndPlayerButton.checked=0!=b[c++];d.sndRightAnswer.checked=
0!=b[c++];d.sndWrongAnswer.checked=0!=b[c++];d.sndFalseStart.checked=0!=b[c++];d.sndClock.checked=0!=b[c++];d.sndTikTok.checked=0!=b[c++];g.onchange()}}):log("Characteristic not found")}let elAudio=document.createElement("audio");document.body.append(elAudio);function playSound(b){elAudio.pause();elAudio.currentTime=0;elAudio.src="snd/"+b+".ogg";elAudio.play();event.preventDefault();event.stopPropagation()}
function onOptionsChange(b){let a=b.elements;var c="GT_FIRST_PRESS"!=a.gameType.value;a.fs_answerTime.disabled=c;a.fs_firstSecondRule.disabled=c;a.fs_onWrongAnswer.disabled=c;a.fs_onNextPlayer.disabled=c;a.fs_onRestartThinkingTime.disabled=c;c="TM_LIMIT"!=a.thinkingTimeMode.value;a.fs_onRestartThinkingTime.disabled=a.fs_onRestartThinkingTime.disabled||c;c="TA_AFTER_SIGNAL"!=a.takeAnswer.value;a.fs_falseStart.disabled=c;a.fs_falseStartBlock.disabled=c;a.fs_firstSecondRule.disabled=a.fs_firstSecondRule.disabled||
c;c=!a.falseStart.checked;a.fs_falseStartBlock.disabled=a.fs_falseStartBlock.disabled||c;c="OWA_NEXT_PLAYER"!=a.onWrongAnswer.value;a.fs_onNextPlayer.disabled=a.fs_onNextPlayer.disabled||c;a.fs_onRestartThinkingTime.disabled=a.fs_onRestartThinkingTime.disabled||c;c="ONP_RESTART_THINKING_TIME"!=a.onNextPlayer.value;a.fs_onRestartThinkingTime.disabled=a.fs_onRestartThinkingTime.disabled||c;b=b.querySelector(".leds");b.children[0].classList.value="led";b.children[1].classList.value="led";b.children[5].classList.value=
"led";c=a.showFalseStart.checked?1:0;a.showFalseStart.checked&&b.children[0].classList.add("false-start");a.showWrongAnswer.checked&&b.children[c].classList.add("wrong-answer");a.showNextReadyToAnswer.checked&&b.children[5].classList.add("next-answer")}
function selectTab(b){let a=b.parentElement.children,c=0;for(let e=0;e<a.length;e++)a[e].classList.remove("active"),a[e]==b&&(c=e);b.classList.add("active");a=document.querySelector(".tabs").children;for(b=0;b<a.length;b++)a[b].classList.remove("active");a[c].classList.add("active")}
function addGame(){let b=document.querySelector(".tab-selector"),a=b.children.length-1;b.children[a].insertAdjacentHTML("beforebegin",'\x3cbutton onclick\x3d"selectTab(this)"\x3e'+(a+1)+"\x3c/button\x3e");6<=a+1&&addGameBtn.classList.add("hidden");2<b.children.length&&deleteGameBtn.classList.remove("hidden");let c=gameTemplate.content.cloneNode(!0),e=c.children[0];document.querySelector(".tabs").appendChild(c);e.onchange();b.children[a].click();return e}
function deleteGame(){let b=document.querySelector(".tab-selector");var a=document.querySelector(".tabs \x3e .active");a.remove();a=b.querySelector(":scope \x3e .active");let c=a.previousElementSibling?a.previousElementSibling:a.nextElementSibling;a.remove();c.click();for(a=0;a<b.children.length-1;a++)b.children[a].innerText=a+1;2==b.children.length&&deleteGameBtn.classList.add("hidden");addGameBtn.classList.remove("hidden")}addGame();

